-- 코드를 입력하세요
SELECT products.PRODUCT_ID, products.PRODUCT_NAME, 
    SUM(AMOUNT *PRICE ) AS TOTAL_SALES

FROM FOOD_PRODUCT products JOIN FOOD_ORDER orders
ON products.PRODUCT_ID = orders.PRODUCT_ID
WHERE PRODUCE_DATE <= DATE('2022-05-31')
AND PRODUCE_DATE >= DATE('2022-05-01')
GROUP BY products.PRODUCT_ID, products.PRODUCT_NAME
ORDER BY TOTAL_SALES DESC, products.PRODUCT_ID ASC