-- // 서로 ID 없는 것이 존재함. => UNION 으로 우선 합치는 게 맞는 듯하다.

WITH TOTAL_TABLE AS (
    SELECT *
    FROM FIRST_HALF 

    UNION ALL
    
    SELECT *
    FROM JULY
)

SELECT FLAVOR #, SUM(TOTAL_ORDER)
FROM TOTAL_TABLE
GROUP BY FLAVOR
HAVING SUM(TOTAL_ORDER) > 0
ORDER BY SUM(TOTAL_ORDER) DESC
LIMIT 3

    