SELECT HISTORY_ID,
CASE
    WHEN ((DATEDIFF(END_DATE, START_DATE) + 1) >= 90) 
    THEN  ROUND(car.DAILY_FEE * (DATEDIFF(END_DATE, START_DATE) + 1) * 
     ((100 - (SELECT DISCOUNT_RATE FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN plan 
     WHERE car.CAR_TYPE = plan.CAR_TYPE AND DURATION_TYPE = '90일 이상')) / 100))
    
    WHEN ((DATEDIFF(END_DATE, START_DATE) + 1) >= 30) 
    THEN  ROUND(car.DAILY_FEE * (DATEDIFF(END_DATE, START_DATE) + 1) * 
     ((100 - (SELECT DISCOUNT_RATE FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN plan 
     WHERE car.CAR_TYPE = plan.CAR_TYPE AND DURATION_TYPE = '30일 이상')) / 100))
    
    WHEN ((DATEDIFF(END_DATE, START_DATE) + 1) >= 7) 
    THEN  ROUND(car.DAILY_FEE * (DATEDIFF(END_DATE, START_DATE) + 1) * 
     ((100 - (SELECT DISCOUNT_RATE FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN plan 
     WHERE car.CAR_TYPE = plan.CAR_TYPE AND DURATION_TYPE = '7일 이상')) / 100))
    
    ELSE car.DAILY_FEE * (DATEDIFF(END_DATE, START_DATE) + 1)
END AS FEE



FROM CAR_RENTAL_COMPANY_CAR car JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY history
ON car.CAR_ID = history.CAR_ID
WHERE car.CAR_TYPE = '트럭'
ORDER BY FEE DESC, HISTORY_ID DESC;