-- 코드를 작성해주세요
WITH ECOLI1 AS (
    SELECT *
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
), ECOLI2 AS (
    SELECT *
    FROM ECOLI_DATA
    WHERE PARENT_ID IN (SELECT ID FROM ECOLI1)
)

SELECT ID
FROM ECOLI_DATA
WHERE PARENT_ID IN (SELECT ID FROM ECOLI2)
ORDER BY ID