WITH ECOLI_RANK AS (
    SELECT ID,
    RANK() OVER (ORDER BY SIZE_OF_COLONY DESC) AS RK,
    COUNT(*) OVER () AS TOTAL_CNT
    FROM ECOLI_DATA
)

SELECT ID,
    CASE 
        WHEN RK <= TOTAL_CNT * 0.25 THEN 'CRITICAL'
        WHEN RK <= TOTAL_CNT * 0.5 THEN 'HIGH'
        WHEN RK <= TOTAL_CNT * 0.75 THEN 'MEDIUM'
        ELSE 'LOW'
        
    END AS COLONY_NAME
FROM ECOLI_RANK
ORDER BY ID;